version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: environment/dockerfiles/app.dockerfile
      args:
        xdebug: "true"
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www:delegated
    env_file:
      - environment/docker.env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - 9000:9000

  web:
    build:
      context: ./
      dockerfile: environment/dockerfiles/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    ports:
      - 8080:80

volumes:
  dbdata: